// The page leads with project evidence. Personal history stays in config/cv.json.
export const ABOUT = {
  title: 'About me',
  description: 'Head of AI Content at Debenhams Group. From motion design for Debenhams to two years focused on AI, and now group-level AI integration.',
  eyebrow: '00 / About me',
  role: 'Head of AI Content',
  employer: 'Debenhams Group',
  heading: 'A bit about me.',
  biography: [
    'I hate talking about myself. Naturally, I’ve made a whole page for it.',
    'I joined Debenhams as a Motion Designer for the brand. I then spent two years focused solely on AI content, workflows and production tools, before my role changed to Head of AI Content with a group-wide remit.',
    'My background is in motion design, 3D and video, so making the work still matters to me. But I’m just as interested in how it gets made: what the team needs, where a process gets stuck and what’s worth building to help.',
    'That’s where the creative, strategy and technical parts of my role meet. This is how I got from making the content to building the tools around it.',
  ],
  introduction: 'PRTFLO is a personal project that shows how I approach that work.',
  contactLabel: 'Get in touch',
  collectionLabel: 'Explore the collection',
  portrait: {
    src: '/about/journey/america-01.webp',
    alt: 'Elliott Quashie speaking during an industry discussion in America',
    position: '68% 50%',
    scale: 1.2,
    placeholder: 'Portrait to follow',
  },
  timeline: {
    label: 'From brief to delivery',
    skipLabel: 'Next',
    backLabel: 'Back to the start',
    cvLabel: 'Jump to CV',
    chapters: [
      { id: 'introduction', number: '01', label: 'Introduction' },
      { id: 'project', number: '02', label: 'Brief to output' },
      { id: 'production', number: '03', label: 'Build the workflow' },
      { id: 'quality', number: '04', label: 'Review the detail' },
      { id: 'teams', number: '05', label: 'Make it repeatable' },
      { id: 'cv', number: '06', label: 'CV & contact' },
    ],
  },
  project: {
    title: 'One brief. A whole collection.',
    type: 'PRTFLO / Self-directed / SS26',
    brief: 'Create a fictional fashion house. Deliver the catalogue, campaign and storefront.',
    metrics: ['Product concepts', 'Published images', 'Departments'],
    detailsLabel: 'The brief & my role',
    details: 'This self-directed project connects product concepts, visual direction, generated imagery, campaign motion and the design and build of the storefront.',
    filmLabel: 'Watch the campaign film',
    filmTitle: 'PRTFLO campaign film',
    contactSheetLabel: 'Selected images from the published collection',
  },
  production: {
    title: 'References in. A shot set out.',
    body: 'One product, shown through the actual inputs and output.',
    modelLabel: 'Model reference',
    garmentLabel: 'Garment reference',
    outputLabel: 'Generated output',
    note: 'All three images are generated.',
    detailsLabel: 'Inside the workflow',
    details: 'Product codes and shared instructions connect the shot list to generation, review and web delivery. The product’s workflow panel contains its generation record.',
    productLink: 'Open the workflow record',
    sourceAlt: 'Generated garment reference for the heavyweight boxy tee',
    modelAlt: 'Marlon, generated model reference',
    outputAlt: 'Generated front view of the heavyweight boxy tee on Marlon',
  },
  quality: {
    title: 'Get closer.',
    body: 'Inspect the seams, fabric and continuity across the set.',
    detailAlt: 'Close-up of the generated tee showing contrast sleeve stitching and the side seam',
    detailLabel: 'Contrast stitching / fabric texture',
    views: ['Front', 'Editorial', 'Detail', 'Back'],
    viewSet: 'Inspect the full set',
    detailsLabel: 'Review criteria',
    details: 'Check the silhouette, colour and construction against the reference, then compare the full set. Review at delivery size before release. These published views show the output; they are not a documented before-and-after correction.',
  },
  teams: {
    title: 'The files behind the work.',
    body: 'Reusable instructions. Named assets. A defined output set.',
    files: [
      { title: 'Generation instructions', type: 'Markdown', href: '/about/generation-instructions.md', preview: ['01  Shared lighting', '02  Composition rules', '03  Material treatment'], action: 'Download instructions' },
      { title: 'Asset manifest', type: 'JSON', href: '/about/asset-manifest.json', preview: ['PRTM01_INK_01', 'PRTM01_INK_02', 'PRTM01_INK_03', 'PRTM01_INK_04'], action: 'Download manifest' },
    ],
    detailsLabel: 'Taking this into a team',
    details: 'These are working files from an individual project. A team pilot would add a named review owner, a walkthrough and a trial run by another person before scaling.',
  },
  cv: {
    title: 'Keep a copy.',
    note: 'From motion design to group-wide AI integration. The experience, the work and how I approach it.',
    previewLabel: 'Read the CV on this page',
  },
} as const;
