import type { StylingCategory, StylingSelection, StyledOutput } from '@/lib/styling-demo';

export interface DemoLook {
  id: string;
  name: string;
  model: string;
  garment: string;
  primary: string;
  back: string;
  derivatives: string[];
  styling: StylingSelection;
  stylingReference: string;
  wornWith: { category: string; label: string }[];
  stylingNote?: string;
}

const sample = (id: string, name: string, slug: string, bottom: string, footwear: string, front: string, fullLook: string, wornWith: DemoLook['wornWith'], stylingNote?: string): DemoLook => {
  const root = `/products/men/${slug}`;
  return { id, name, model: '/models/marlon.webp', garment: `${root}/ref-01.webp`, primary: `${root}/${front}.webp`, back: `${root}/04.webp`, derivatives: [`${root}/${front === '01' ? '02' : '01'}.webp`, `${root}/03.webp`], styling: { top: id, bottom, footwear, pose: 'relaxed', model: 'marlon' }, stylingReference: `${root}/${fullLook}.webp`, wornWith, stylingNote };
};

// Styling is classified from these existing full-look ecommerce images.
// The pipeline only reveals saved views; it does not create or restyle images.
export const DEMO_LOOKS: DemoLook[] = [
  sample('PRTM01', 'Navy boxy tee', 'heavyweight-boxy-tee', 'black-trousers', 'black-loafers', '01', '02', [
    { category: 'Bottoms', label: 'Cropped black trousers' },
    { category: 'Footwear', label: 'Black loafers' },
    { category: 'Editorial layer', label: 'Ecru high-neck underlayer' },
  ], 'The ecru layer appears in the editorial and detail images; the catalogue front and back show the tee on its own.'),
  sample('PRTM02', 'Green slogan tee', 'garment-dyed-slogan-tee', 'black-jeans', 'tan-shoes', '02', '01', [
    { category: 'Bottoms', label: 'Washed black jeans' },
    { category: 'Footwear', label: 'Tan lace-up shoes' },
  ]),
  sample('PRTM03', 'Oxblood crew tee', 'heavyweight-crew-tee', 'ecru-trousers', 'brown-sandals', '02', '02', [
    { category: 'Bottoms', label: 'Wide-leg ecru trousers' },
    { category: 'Footwear', label: 'Brown sandals' },
  ]),
];

export interface StylingOption { id: string; label: string; image?: string }
export interface StylingGroup { id: StylingCategory; label: string; options: StylingOption[] }
export const STYLING_GROUPS: StylingGroup[] = [
  { id: 'top', label: 'Top', options: DEMO_LOOKS.map((look) => ({ id: look.id, label: look.name, image: look.garment })) },
  { id: 'bottom', label: 'Bottoms', options: [
    { id: 'black-trousers', label: 'Cropped black trousers' },
    { id: 'black-jeans', label: 'Washed black jeans' },
    { id: 'ecru-trousers', label: 'Wide-leg ecru trousers' },
  ] },
  { id: 'footwear', label: 'Footwear', options: [
    { id: 'black-loafers', label: 'Black loafers' },
    { id: 'tan-shoes', label: 'Tan lace-up shoes' },
    { id: 'brown-sandals', label: 'Brown sandals' },
  ] },
  { id: 'pose', label: 'Primary view', options: [
    { id: 'relaxed', label: 'Catalogue view' },
    { id: 'editorial', label: 'Alternate view' },
  ] },
  { id: 'model', label: 'Model', options: [
    { id: 'marlon', label: 'Marlon', image: '/models/marlon.webp' },
  ] },
];

// Both primary choices come from the existing product shot set.
export const STYLING_OUTPUTS: StyledOutput[] = DEMO_LOOKS.flatMap((look) => [
  { selection: look.styling, primary: look.primary, back: look.back, derivatives: look.derivatives },
  { selection: { ...look.styling, pose: 'editorial' }, primary: look.derivatives[0], back: look.back, derivatives: [look.primary, look.derivatives[1]] },
]);

export const STYLING_COPY = {
  title: 'Already styled.',
  description: 'Explore the outfit shown in the existing ecommerce image.',
  reference: 'Full-look styling reference',
  brief: 'Download example brief',
  changed: 'Primary view updated. Review decisions have been reset.',
  blocked: 'This example needs its existing shot set before continuing.',
  classification: 'Styled with',
  note: 'Styling labels describe the pictured outfit. They are indicative, not separate catalogue products.',
  edit: 'Back to outfit', selection: 'Choose the primary image', look: 'Look',
  needsOutput: 'Image unavailable',
} as const;

export const BATCH_DEMO = {
  title: 'An example through the pipeline.',
  disclosure: 'Indicative demo using existing PRTFLO ecommerce images. No live generation or delivery.',
  provenance: 'Styling labels describe the saved imagery. The stages illustrate a production workflow; these images were not generated by this demo.',
  steps: [
    { label: 'Outfit', detail: 'See what the existing look is styled with.' },
    { label: 'Primary', detail: 'Choose an existing image to lead the example shot set.' },
    { label: 'Back', detail: 'Inspect the saved back view.' },
    { label: 'Details', detail: 'Explore the other images in the existing set.' },
    { label: 'Review', detail: 'Try approving or holding each example look.' },
    { label: 'Delivery', detail: 'Preview a manifest containing only your approved examples.' },
  ],
  labels: {
    next: 'Next', reset: 'Reset demo', approve: 'Approve', hold: 'Hold', pending: 'Needs review', approved: 'Approved', held: 'Held', reviewAgain: 'Review again',
    queue: 'Example batch', model: 'Model reference', garment: 'Garment reference', primary: 'Saved primary image', back: 'Saved back view', derivative: 'Existing additional view',
    manifest: 'Download example manifest', ready: 'Preview delivery', complete: 'Example manifest ready. No assets have been sent.',
    reviewHint: 'Review each look to continue. At least one must be approved.', empty: 'No approved looks.',
    retryHint: 'Returned to review. This preview reuses the existing images.',
  },
} as const;
