export const COPY = {
  landing: {
    eyebrow: 'Portfolio · not a real shop',
    framing:
      'A fictional fashion house, built as a portfolio piece. Every image here is AI-generated; there was never a photo shoot. Have a look around as if it were real.',
    enterLabel: 'Enter the collection',
    aboutLabel: 'About the project',
  },
  home: {
    heroEyebrow: 'Spring / Summer 2026',
    heroHeading: 'A designer label of one.',
    heroSubcopy:
      'Season-less drops, a tight palette, an obsession with how the work is seen. Crafted in technical fabric. Cut to sit close.',
    primaryCta: { label: 'View the catalogue', href: '/women' },
    secondaryCta: { label: 'About the project', href: '/intro' },
  },
  campaign: {
    eyebrow: 'Campaign · SS26',
    heading: 'The season campaign.',
    body: 'Staged entirely in the pipeline: no location, no crew. Just the garments, placed wherever they need to be.',
    cta: { label: 'How this is made', href: '/intro' },
    image: '/campaign/ss26-01.webp',
  },
  gate: {
    eyebrow: 'Private preview',
    prompt: 'You were given a word. Use it.',
    placeholder: 'Password',
    submitLabel: 'Enter',
    errorWrong: 'That isn’t it.',
    errorUnavailable: 'The door isn’t configured. Come back later.',
  },
  intro: {
    arrival: {
      eyebrow: 'You’re in',
      heading: 'Not a real shop.',
      sub: 'A working fashion house where every image is generated. There’s no studio behind any of this, just a pipeline.',
      scrollCue: 'Scroll',
    },
    plates: [
      'The garments are real product concepts, designed, named, and priced like a label you could actually buy from.',
      'The images are another story. No photographer, no model, no set. What looks like a campaign came out of a prompt and a pipeline.',
      'The storefront is meant to feel like the genuine article. If you believed it for a moment, it did its job.',
    ],
    reveal: {
      eyebrow: 'The reveal',
      heading: 'Same shot, two ways.',
      sub: 'Drag across the frame. The studio version is on one side, the generated one on the other.',
    },
    exit: {
      heading: 'Go have a look.',
      sub: 'Browse the catalogue the way a customer would: open a product, switch the currency, add something to the basket. None of it was photographed.',
      ctaLabel: 'Enter the collection',
    },
  },
  basket: {
    title: 'Basket',
    empty: 'Your basket is empty.',
    emptyCta: 'View the catalogue',
    subtotalLabel: 'Subtotal',
    deliveryLabel: 'Delivery',
    deliveryValue: 'Complimentary',
    totalLabel: 'Total',
    checkoutLabel: 'Checkout',
    reassurance: 'Complimentary delivery and 30-day returns on every order.',
  },
  checkout: {
    title: 'Checkout',
    steps: ['Basket', 'Delivery', 'Payment'],
    empty: 'There is nothing to check out.',
    emptyCta: 'View the catalogue',
    delivery: {
      nameLabel: 'Full name',
      emailLabel: 'Email',
      submitLabel: 'Continue to payment',
    },
    processing: 'Confirming your order…',
    reveal: {
      stepLabel: 'Disclosure',
      heading: 'This is as far as it goes.',
      body: 'None of the pieces in this order exist. They’re product concepts, and every image of them was generated. You browsed the range, chose a size, and made it to the till. That was the whole demonstration.',
      orderLabel: 'Your order',
      imageryLabel: 'What the imagery cost to make',
      studioLabel: 'What a studio shoot would have cost',
      imageryNote: 'Those two figures cover the same set of shots, the ones that just sold you this order.',
      contactHeading: 'What this actually is',
      contactBody:
        'PRTFLO is my portfolio piece: one designer running a full catalogue on a generation pipeline. If you need something like this built, whether a range, a campaign, or a whole storefront, I’d be glad to talk.',
      contactCta: 'Get in touch',
      secondaryCta: 'How it was made',
      keepBrowsing: 'Keep browsing',
    },
  },
  pipeline: {
    eyebrow: 'Pipeline',
    heading: 'There was no shoot.',
    sub: 'A model who doesn’t exist, a garment never sewn, a backdrop never built, all put together in the pipeline. Here’s the record of making this piece:',
    equation: {
      model: 'Model',
      mannequin: 'Mannequin',
      backdrop: 'Backdrop',
      final: 'Final shot',
    },
    labels: {
      frames: 'Frames',
      attempts: 'Attempts',
      time: 'Time in pipeline',
      costPerAttempt: 'Cost per attempt',
      total: 'Generation total',
      studio: 'Studio equivalent',
    },
    footnoteAverage:
      'These are house averages from the SS26 run. Per-piece figures take over once a run is logged.',
    footnoteLogged: 'Logged from this piece’s generation run.',
    referenceLabel: 'Generation reference',
    closingLine: 'That total includes every frame that got thrown away.',
  },
  about: {
    heading: 'About this project',
    body: 'PRTFLO is a fictional fashion house I built as a portfolio piece. The garments are original concepts, designed, named, and priced like a real label. Every image was generated rather than photographed. The site exists to show the work.',
  },
} as const;
