export const COPY = {
  landing: {
    eyebrow: 'AI orchestration · Batch automation',
    heading: 'Explore the result.',
    framing:
      'Creative direction, AI generation and batch automation, brought together in a complete fashion storefront. Explore the output, then meet the person who built the workflow.',
    enterLabel: 'Storefront',
    storeDescription: 'See the workflow in action: a full catalogue of AI-generated imagery, produced through batch automation and brought together in a working storefront.',
    aboutLabel: 'About Me',
    aboutDescription: 'How I connect creative direction, AI tools and automation to build repeatable production workflows.',
    workflowHint:
      'Flip this on and every image in the store shows what it cost to generate against a studio equivalent. It stays on while you browse.',
  },
  home: {
    heroEyebrow: 'Spring / Summer 2026',
    heroHeading: 'A designer label of one.',
    heroSubcopy:
      'Season-less drops, a tight palette, an obsession with how the work is seen. Crafted in technical fabric. Cut to sit close.',
    primaryCta: { label: 'View the catalogue', href: '/women' },
    secondaryCta: { label: 'About the project', href: '/intro' },
  },
  campaign: {
    eyebrow: 'Campaign · SS26',
    heading: 'The season campaign.',
    body: 'Staged entirely in the workflow: no location, no crew. Just the garments, placed wherever they need to be.',
    cta: { label: 'How this is made', href: '/intro' },
    image: '/campaign/ss26-01.webp',
  },
  gate: {
    eyebrow: 'Elliott Quashie · Private portfolio',
    heading: 'PRTFLO',
    introduction: 'From product concepts and campaign imagery to the site itself, PRTFLO was built using AI. I designed and orchestrated the workflows, using batch automation to turn a creative brief into a complete fashion storefront.',
    prompt: 'Enter the password to explore the Storefront and About Me. PRTFLO is a fictional fashion house and a portfolio project, not a real shop.',
    placeholder: 'Password',
    submitLabel: 'Unlock portfolio',
    pendingLabel: 'Unlocking…',
    errorWrong: 'Incorrect password. Please try again.',
    errorUnavailable: 'Access is temporarily unavailable. Please try again later.',
  },
  intro: {
    arrival: {
      eyebrow: 'From brief to storefront',
      heading: 'A whole collection. One connected workflow.',
      sub: 'PRTFLO brings creative direction, AI generation and batch automation together: product concepts become complete image sets, organised and delivered into a working storefront. A fictional fashion house, built to demonstrate the process.',
      scrollCue: 'Scroll',
    },
    plates: [
      'The garments are real product concepts, designed, named, and priced like a label you could actually buy from.',
      'The images are another story. No photographer, no model, no set. What looks like a campaign came out of a prompt and a workflow.',
      'The storefront is meant to feel like the genuine article. If you believed it for a moment, it did its job.',
    ],
    reveal: {
      eyebrow: 'The reveal',
      heading: 'Same shot, two ways.',
      sub: 'Drag across the frame. The studio version is on one side, the generated one on the other.',
    },
    exit: {
      heading: 'Go have a look.',
      sub: 'Browse the catalogue the way a customer would: open a product, switch the currency, add something to the basket. None of it was photographed.',
      ctaLabel: 'Enter the collection',
    },
  },
  basket: {
    title: 'Basket',
    empty: 'Your basket is empty.',
    emptyCta: 'View the catalogue',
    subtotalLabel: 'Subtotal',
    deliveryLabel: 'Delivery',
    deliveryValue: 'Complimentary',
    totalLabel: 'Total',
    checkoutLabel: 'Checkout',
    reassurance: 'Complimentary delivery and 30-day returns on every order.',
  },
  checkout: {
    title: 'Checkout',
    steps: ['Basket', 'Delivery', 'Payment'],
    empty: 'There is nothing to check out.',
    emptyCta: 'View the catalogue',
    delivery: {
      nameLabel: 'Full name',
      emailLabel: 'Email',
      submitLabel: 'Continue to payment',
    },
    processing: 'Confirming your order…',
    reveal: {
      stepLabel: 'Disclosure',
      heading: 'This is as far as it goes.',
      body: 'None of the pieces in this order exist. They’re product concepts, and every image of them was generated. You browsed the range, chose a size, and made it to the till. That was the whole demonstration.',
      orderLabel: 'Your order',
      imageryLabel: 'What the imagery cost to make',
      studioLabel: 'What a studio shoot would have cost',
      imageryNote: 'Those two figures cover the same set of shots, the ones that just sold you this order.',
      contactHeading: 'What this actually is',
      contactBody:
        'PRTFLO is my portfolio piece: one designer running a full catalogue on a generation workflow. If you need something like this built, whether a range, a campaign, or a whole storefront, I’d be glad to talk.',
      contactCta: 'Get in touch',
      secondaryCta: 'How it was made',
      keepBrowsing: 'Keep browsing',
    },
  },
  pipeline: {
    eyebrow: 'Workflow',
    heading: 'There was no shoot.',
    subApparel:
      'The model, garment, and backdrop are generated, not photographed, then combined.',
    subHome: 'The object and backdrop are generated, not photographed, then combined.',
    equation: {
      model: 'Model',
      mannequin: 'Mannequin',
      object: 'Object',
      backdrop: 'Backdrop',
      final: 'Final shot',
    },
    labels: {
      frames: 'Frames',
      attempts: 'Attempts',
      time: 'Time in workflow',
      costPerAttempt: 'Cost per attempt',
      total: 'Generation total',
      studio: 'Studio equivalent',
    },
    footnoteAverage:
      'These are house averages from the SS26 run. Per-piece figures take over once a run is logged.',
    footnoteLogged: 'Logged from this piece’s generation run.',
    referenceLabel: 'Generation reference',
    closingLine: 'That total includes every frame that got thrown away.',
  },
  about: {
    heading: 'About this project',
    body: 'PRTFLO is a fictional fashion house I built as a portfolio piece. The garments are original concepts, designed, named, and priced like a real label. Every image was generated rather than photographed. The site exists to show the work.',
  },
} as const;
